apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-prediction
  namespace: house-price-prediction
  labels:
    app: house-price-prediction
    app.kubernetes.io/name: house-price-prediction
    app.kubernetes.io/part-of: ml-applications
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-price-prediction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: house-price-prediction
    spec:
      containers:
      - name: house-price-prediction
        image: <your-docker-hub-username>/house-price-prediction:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8501
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 10
        env:
        - name: PORT
          value: "8501"
