apiVersion: v1
kind: Service
metadata:
  name: house-price-prediction
  namespace: house-price-prediction
  labels:
    app: house-price-prediction
    app.kubernetes.io/name: house-price-prediction
    app.kubernetes.io/part-of: ml-applications
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: house-price-prediction
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP
  type: LoadBalancer
